"""empty message

Revision ID: 36d2b461a823
Revises: 7397fe6a4860
Create Date: 2020-12-02 22:10:04.333644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d2b461a823'
down_revision = '7397fe6a4860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'city')
    op.drop_column('credit_card', 'expiration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card', sa.Column('expiration_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
